name: test cucumbers
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2

    - name: Configuration de Java
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        distribution: 'jdk'

    - name: Configuration de Maven
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        distribution: 'maven'

    - name: Construction du projet
      run: mvn clean install

    - name: Ex√©cution des tests
      run: mvn test
